{"name": "test_C001003", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 2", "trace": "self = <test_login.Test_error object at 0x000001BA8660AC08>\n\n    def test_C001003(self):\n        print('\\n用例C001003')\n>       assert 3 == 2\nE       assert 3 == 2\n\ntestcase\\login\\test_login.py:13: AssertionError"}, "start": 1743663871446, "stop": 1743663871446, "uuid": "16681c70-55bb-462e-910b-ea43f1122812", "historyId": "958929d122f4809e19827bf04dfb49bb", "testCaseId": "958929d122f4809e19827bf04dfb49bb", "fullName": "testcase.login.test_login.Test_error#test_C001003", "labels": [{"name": "parentSuite", "value": "testcase.login"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_error"}, {"name": "host", "value": "DESKTOP-QOMHOVE"}, {"name": "thread", "value": "17076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.login.test_login"}]}